name = "hugo-globetrail-theme"
license = "MIT"
# licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = ""
homepage = "https://github.com/splatrac/hugo-globetrail-theme"
min_version = "0.134.3"

tags = [
    "blog",
    "responsive",
    "personal",
    "light",
    "bootstrap",
    "portfolio",
    "landing",
    "company",
    "modern",
]
features = []

[author]
name = "Splatrac"
homepage = "https://splatrac.me/"
