main:
  - name: home
    url: "#home"
    weight: 10
  - name: about_us
    url: "/"
    weight: 20
  - name: destination
    url: "#destination"
    weight: 30
  - name: packages
    url: "#packages"
    weight: 40
  - name: gallery
    url: "#gallery"
    weight: 50
  - name: contact_us
    url: "#contact"
    weight: 60
social_list:
  - name: facebook
    url: "#"
    weight: 10
  - name: twitter
    url: "#"
    weight: 20
  - name: youtube
    url: "#"
    weight: 30
footer:
  - name: privacy_policy
    url: /privacy-policy
    weight: 10
  - name: terms_n_cond
    url: /term-and-condition
    weight: 20
  - name: FAQ
    url: /faq
    weight: 30
