DefaultContentLanguage = "en"
baseURL = "/"
languageCode = "en-us"
title = "Globetrail Theme"
summaryLength = 20
[module]
# replacements = "github.com/splatrac/hugo-globetrail-theme -> ../"
[[module.imports]]
ignoreConfig = false
disable = false
# path = "../"
path = "github.com/splatrac/hugo-globetrail-theme"


[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "layouts"
target = "layouts"
[[module.mounts]]
source = "content"
target = "content"
[[module.mounts]]
source = "data"
target = "data"

[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "i18n"
target = "i18n"

[[module.mounts]]
source = "archetypes"
target = "archetypes"

[module.hugoVersion]
extended = true
min = "0.124.0"

[params]
phoneNumber = "+30 210 6068826"
